name: Run Android Emulator on PR
on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Accept Licenses
        run: yes | sdkmanager --licenses

      - name: Install Emulator and System Image
        run: |
          sdkmanager "platform-tools" "emulator" "platforms;android-30" "system-images;android-30;google_apis;x86_64"
          echo "y" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force

      - name: Start Android Emulator
        run: |
          nohup emulator -avd test -no-snapshot -no-audio -no-boot-anim -gpu swiftshader_indirect > /dev/null 2>&1 &
          adb wait-for-device
          boot_completed=""
          until [[ "$boot_completed" == "1" ]]; do
            sleep 5
            boot_completed=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
            echo "Waiting for emulator to boot... ($boot_completed)"
          done
          echo "Emulator booted!"

      - name: Run Tests
        run: npm run wdio
