name: Run Android Emulator on PR
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Install emulator and x86 system image
        run: |
          sdkmanager "platform-tools" "emulator" "platforms;android-30" "system-images;android-30;google_apis_playstore;x86_64"
          avdmanager create avd -n test -k "system-images;android-30;google_apis_playstore;x86_64" --device "pixel" --force

      - name: Start Android Emulator
        run: |
          echo "Starting emulator..."
          nohup emulator -avd test -no-audio -no-window -no-snapshot -gpu swiftshader_indirect > emulator.log 2>&1 &

          echo "Waiting for emulator to boot..."
          timeout=300
          elapsed=0
          until adb shell getprop sys.boot_completed 2>/dev/null | grep -m 1 "1"; do
            if [ $elapsed -ge $timeout ]; then
              echo "⛔ Timeout waiting for emulator to boot after $timeout seconds."
              echo "--- Emulator log ---"
              cat emulator.log
              exit 1
            fi
            sleep 5
            elapsed=$((elapsed + 5))
            echo "Still waiting... ($elapsed seconds)"
          done
          echo "✅ Emulator booted successfully."

      - name: Run Tests
        run: npm run wdio
